manifest:
  remotes:
    - name: tklzg
      url-base: https://github.com/tklzg
  projects:
    - name: zmk_test
      remote: tklzg
      revision: waterfowl-encoders
      import: app/west.yml
  self:
    path: config
