manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: genkobar
      url-base: https://github.com/genkobar/zmk.git
  projects:
    - name: zmk
      remote: genkobar
      revision: split-encoder
      import: app/west.yml
  self:
    path: config
