manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: DiogoDoreto
      url-base: https://github.com/DiogoDoreto
    - name: tklzg
      url-base: https://github.com/tklzg
  projects:
    - name: zmk
      remote: tklzg
      revision: main
      import: app/west.yml
  self:
    path: config
